### ISSUE TITLE
Application fails to start with put-it-to-rest

### ISSUE THREAD

**Issue by divinedragon** [zalando-stups/put-it-to-rest#67]
I am trying to integrated this, but I am getting the exception below

```
Binding to target org.zalando.putittorest.RestSettings@478d8326 failed:

    Property: rest.clients[myservice].connectionTimeout
    Value: 5 seconds
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'org.zalando.putittorest.TimeSpan' for property 'clients[membership].connectionTimeout'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.zalando.putittorest.TimeSpan]
```

My configuration seems be ok.

```yaml
rest:
  oauth:
    access-token-url: https://token.example.com
  defaults:
    plugins:
      - original-stack-trace
      - temporary-exception
  clients:
    myservice:
      baseUrl: https://service.example.com
      connection-timeout: 5 seconds
      socket-timeout: 10 seconds
      max-connections-per-route: 10
      oauth:
        scopes:
          - uid
          - service.read
```
