### ISSUE TITLE
Add support for failsafe

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-stups/put-it-to-rest#71]
Requires zalando/riptide#218.

Proposed configuration

```yaml
rest.clients:
  example:
    failsafe: # only needed if we keep hystrix as an alternative, not sure if I actually want to
      retry:
        fixed-delay: 1 second
        exponentional-backoff:
          delay: 500 millis
          max-delay: 3 seconds
          delay-factor: 2 # default
        max-retries: 3
        max-duration: 5 seconds
        jitter: 0.1
      circuit-breaker:
        failure-threshold: 5
        delay: 1 minute
        success-threshold: 5
```

Should use `failsafe-actuactor`'s [`CircuitBreakerRegistry`](https://github.com/zalando-incubator/failsafe-actuator/blob/master/src/main/java/org/zalando/failsafeactuator/service/CircuitBreakerRegistry.java) for creating circuit breakers.
